vars/slackSend.groovy

SlackSend stub

---

examples/parallelOrchestration.groovy
src/com/base2/ciinabox/JobOrchestration.groovy
src/com/base2/ciinabox/PipelineUtils.groovy

see `examples/parallelOrchestration.groovy` for usage example.

Ciinabox pipelines orchestration library with example

---

vars/lookupAMI.groovy

searching for amazon ami's can return instance store amis. Hardcoding it to ebs.

fix ami search to root-device-type = ebs

---

vars/s3Put.groovy

With ability to set public read permissions on the file

put file to s3 bucket

---

vars/newrelic.groovy

Track deployments in newrelic via the newrelic deployments API.
This step will lookup the newrelic application ID based on the `application` parameter, and register a deployment for that application by the user specified in the `user` parameter with a revision based on the short commit of the source code.

Add newrelic notifier

---

vars/bakeAMI.groovy

Open a new PR for this change as I wanted a clean PR to merge with just this refactored change

allows skiping the uploading of coobooks to the instance prior to baking

---

vars/codedeploy.groovy

currently only supports triggering codedeploy with deployments in S3

adds a step for triggering codedeploy from an bundle stored in S3

---

test/cloudformationTestPipeline.groovy
vars/cloudformation.groovy

If cloudformation bucket is in different region than stack, bucket location needs be discovered before reading template body.

allow cf bucket to be in another region

---

vars/cloudformation.groovy
vars/ecsTask.groovy

Heavy plagarism from https://github.com/base2Services/ciinabox-pipelines/pull/60
Runs a task, waitings for all containers to run and makes sure all containers have an exit status of 0.

Add ability to run a task definition in a particular ECS cluster. 

---

vars/ecr.groovy
vars/ecrScan.groovy

add repo tags, mutable tags and image scanning
will require aws java sdk min 1.11.660

ECR Updates

---

vars/cloudformation.groovy

Add ability to create/update/delete stack without waiting via _waitUntilComplete_ boolean parameter.
Add ability to query the status of a stack, using new queryType value _status_
Add ability to query a stack and wait for it to complete using the new queryType value _status_ and setting the _waitUntilComplete_ boolean parameter to true.

Allow async cloudformation updates

---

resources/packer/download_cookbooks.ps1
resources/packer/ec2_config_service.ps1
resources/packer/ec2_launch_config.ps1
resources/packer/install_7zip.ps1
resources/packer/setup_winrm.ps1
src/com/base2/ciinabox/AwsClient.groovy
src/com/base2/ciinabox/GetInstanceDetails.groovy
src/com/base2/ciinabox/InstanceMetadata.groovy
src/com/base2/ciinabox/PackerTemplateBuilder.groovy
vars/packer.groovy
vars/verifyAMIv2.groovy

example
```groovy
packer(
type: 'windows2012',
role: 'testwin12',
runList: ['demo::windows'],
debug: true,
amiLookupSSM: '/aws/service/ami-windows-latest/Windows_Server-2012-R2_RTM-English-64Bit-Base',
chefVersion: '14.14.25',
cookbookS3Bucket: env.SOURCE_BUCKET,
cookbookS3Path: "chef/demo/${env.VERSION}/cookbooks.tar.gz",
cookbookS3Region: env.REGION
)
````

New packer step

---

vars/cloudformation.groovy

Add ability to query input parameters of existing cloudformation stacks

Add queryStackParams

---

vars/dockerBuild.groovy

Hi, 
I did no tests to this code, but there are also no instruction on the readme.

Allow to use docker build --pull

---

src/com/base2/ciinabox/aws/AwsClientBuilder.groovy
src/com/base2/ciinabox/aws/CloudformationStack.groovy
src/com/base2/ciinabox/aws/CloudformationStackEvents.groovy
vars/createChangeSet.groovy
vars/executeChangeSet.groovy

Example
```groovy
createChangeSet(
description: env.GIT_COMMIT,
region: env.AWS_REGION,
stackName: env.STACK_NAME,
templateUrl: env.TEMPLATE_URL,
parameters: [
'EnvironmentName': env.ENVIRONMET_NAME,
],
roleArn: env.CFN_ROLE
)
input(
message: "Execute changes ${env.DEMO_CHANGESET_DEV_CHANGESET_NAME}"
)
executeChangeSet(
region: env.AWS_REGION,
stackName: env.STACK_NAME
)
```

create and execute cloudformation changesets

---

vars/terraformApply.groovy
vars/terraformDestroy.groovy
vars/terraformPlan.groovy

- creates a terraform plan under a terraform workspace
- artefacts the changes
- stashes the out file `tfplan-${workspace}`
- unstashes the plan
- applies the plan to the workspace
- destroys the terraform stack for a workspace
```groovy
pipeline {
agent {
docker {
image 'base2/terraform:0.12.20'
}
}
stages {
stage('plan') {
steps {
terraformPlan(
workspace: 'dev', 
variables: [
environment: 'dev'
]
)
}
}
stage('deploy dev') {
input {
message "apply terraform dev changes?"
} 
steps {
terraformApply(workspace: 'dev')
}
}
}
```

Terraform Methods

---

src/com/base2/ciinabox/aws/CloudformationStack.groovy
src/com/base2/ciinabox/aws/IntrinsicsYamlConstructor.groovy
vars/cloudformation.groovy

adds support for both changesets and cloudformation methods

support for shorthand cloudformation yaml 

---

src/com/base2/ciinabox/aws/AwsClientBuilder.groovy
vars/createChangeSet.groovy

requires an update of the aws-java-sdk plugin in order for the nested stack change sets requests to be made but is backwards compatible with older sdk versions.

add support for nested changesets

---

vars/createChangeSet.groovy
vars/executeChangeSet.groovy

1. continue on empty changeset https://github.com/base2Services/ciinabox-pipelines/commit/d05365f17fcd256d4eb99bb1b41dccc0eae96940
2. error when stack rolls back successfully https://github.com/base2Services/ciinabox-pipelines/commit/29bce22c4544bd7ea9036560b5bac0a7842ac8cc

Changeset improvements

---

vars/createChangeSet.groovy

I implemented some changes to improve the experience when using stacks with a lot of nested stacks. The AWS changeset still suboptimal, but that's the best they offer us, I guess. 
- Documented `nestedStacks` option
- Added `nestedStackVerboseLogs` and `expandedDetails` options to control the output. It shouldn't be a breaking change at all
- Fix the output to not error when some substacks didn't have a changeset. 
Is this something you'd be interested merging?

RIO-754: improving nested stack support for changeset

---

resources/Inspector.yaml
vars/runInspector.groovy

This is a working version of the AMI test via inspector

AMI test with inspector

---

vars/secretScan.groovy

scan a repository for committed secrets such as AWS keys using the opensource tool [gitleaks](https://github.com/zricethezav/gitleaks)
example usage in a pipeline
```groovy
pipeline {
stages {
stage('scan') {
steps {
secretScan()
}
}
}
}
```
By default the pipeline will fail if a secret is detected using the default gitleaks config.

method to scan for secrets when triggering a pipeline

---

resources/Inspector.yaml
vars/runInspector.groovy

changed the default test run time from 2 minutes (used for testing) to 1 hour, a more appropriate minimum

runInspector - added support for supplying rule arns, timeout and ignore fail on findings

---

src/com/base2/ciinabox/aws/AwsClientBuilder.groovy
src/com/base2/ciinabox/aws/CodeArtifactLogin.groovy
vars/codeArtifactDotnetLogin.groovy
vars/codeArtifactNugetLogin.groovy
vars/codeArtifactPipLogin.groovy
vars/codeArtifactRepository.groovy
vars/withCodeArtifact.groovy
vars/withCodeArtifactTwine.groovy

create a code artifact repository and domain with optional configuration of setting upstream repos
```groovy
codeArtifactRepository(
region: 'us-east-1',
accountId: '111111111111',
domain: 'mydomian',
name: 'my-package',
upstream: ['upstream'],
externalConnections: ['public:pypi']
)
```
retrieve a code artifact token export
```groovy
withCodeArtifact(domain: 'mydomain', repository: 'my-package', format: 'pypi') {
sh 'echo $CODEARTIFACT_TOKEN'
sh 'echo $CODEARTIFACT_ENDPOINT'
}
```
push python package with twine
```groovy
withCodeArtifactTwine(domain: 'mydomain', repository: 'my-package') {
sh 'twine upload --repository codeartifact my-package-0.0.1.tar.gz'
}
```
install packages through pip
```groovy
codeArtifactPipLogin(domain: 'mydomain', repository: 'my-package')
sh 'pip install …
```

code artifact steps

---

resources/Inspector.yaml
vars/runInspector.groovy

runInspector - return the findings in a map and improve error handling 

---

resources/Inspector.yaml
vars/runInspector.groovy

Now has support for accounts without a default subnet/vpc (mostly for older accounts) by handling the subnet the instance is made in manually (this only works if Jenkins is running in ec2 and not fargate, for fargate the subnet will need to be manually specified).

Support for accounts without default subnets/VPCs + some bug fixes

---

src/com/base2/ciinabox/PackerTemplateBuilder.groovy
vars/packer.groovy

Added functionality to allow for packer to update windows AMI's during baking

packer - support for windows update on bake

---

resources/Inspector.yaml
vars/runInspector.groovy

Fixes issues with inspector when account does not have a default vpc/subnet

Inspector - support running test instances in a non default vpc by lookup or provided details

---

vars/changeSetDeploy.groovy
vars/executeChangeSet.groovy

- bug fix for executeChangeSet to resolve no fail on empty changeset 
- new method to orchestrate both create and execute changesets in one

ChangeSets - Improvements

---

vars/runInspector.groovy

Final cleanup and updating doc.

runInspector - improve documentation and set default whitelistings

---

vars/ecr.groovy

Adds permissions to allow lambda to pull containers cross account

feat: adds lambda ecr permissions

---

src/com/base2/ciinabox/PackerTemplateBuilder.groovy
vars/packer.groovy

Add option for cinc instead of chef
Allow specifying EBS config

Add option for cinc instead of chef

---

vars/createChangeSet.groovy

Fix for status reason - Now contains string "No updates are to be performed" aswell.

createChangeSet - Updated status reason to include new reason text

---

vars/takeSnapshot.groovy

Takes a snapshot on-demand, supports Aurora clusters, RDS instances and Redshift clusters.

Add takeSnapshot

---

vars/ecrScan.groovy

- update waiter ecr image scan waiter and handle the sleep interupted exception
- fix up imports
- improve result display

ecrScan - fix waiter timeouts and improve report

---

vars/executeChangeSet.groovy

Added `UPDATE_COMPLETE_CLEANUP_IN_PROGRESS` to allowed states

Added cleanup state to allowed final status
