- vars/dockerBuild.groovy
Older docker api requires `-f` flag for retagging images. Helper function should support adding `-f` tag. In future iterations, it would be need to auto-detect docker  version, and add `-f` tag automatically. 
```
dockerBuild forcetag:true,
.... //other parameters
```
> Force tag for older docker api

- test/cloudformationTestPipeline.groovy
- vars/cloudformation.groovy
`cloudformation action:delete` is fixed and tested
Rather than just management actions for cloudformation step, this step should allow querying existing cloudformation stacks (and their substacks), as well as stack outputs. Consumer selects type of query by passing `queryType` parameter. 
```
stage('query){
steps {
script {
def outValue = cloudformation(stackName: 'ciinabox', 
queryType: 'output',
query: 'CiinaboxBinaryVersion'
region: 'ap-southeast-2')
echo "Deployed ciinabox v${outValue}"
} 
}
}
```
Query element should allow querying substack elements, recursively, dot `.` seperated
```
stage('query){
steps {
script {
def jenkins = cloudformation(stackName: 'ciinabox', 
queryType: 'element',
query: 'ECSServicesStack.jenkinsStack.JenkinsService'
region: 'ap-southeast-2')
echo "Jenkins …
```
> Add query operations to cloudformation step

- vars/withECR.groovy
Prevents the output of the '-e' flag
https://stackoverflow.com/questions/44722341/docker-login-unknown-shorthand-flag-e
> withECR: remove email when logging in to docker.

- src/com/base2/ciinabox/AwsHelper.groovy
- test/cloudformationTestPipeline.groovy
- vars/cloudformation.groovy
- vars/route53.groovy
Route53 step should allow for propagation of route53 records from child to parent zone. Both zones can be in different AWS Accounts where jenkins is running, and accessed through assumed role. 
```
route53(
action: 'propagateNs'
srcZone: 'app1.subdomain.example.com'
dstZone: 'example.com',
srcZoneAccount: '123456789012',
srcZoneRole: 'MyRoute53AccessRoleInParentZoneOptionalParam',
srcZoneRoleExternalId: 'optional-external-id-for-route53-zone-role',
dstZoneAccount: '123456789012',
dstZoneRole: 'MyRoute53AccessRoleInParentZoneOptionalParam',
dstZoneRoleExternalId: 'optional-external-id-for-route53-zone-role',
TTL: 300 # defaults to 5 minutes
)
```
```
@Library('ciinabox') _
pipeline {
agent any
stages {
stage('propagate-route53-zone'){
steps {
route53 action:'propagateNs',
srcZone: …
```
> route53 step

- test/cloudformationTestPipeline.groovy
- vars/cloudformation.groovy
Cloudformation create/update/delete operation would not report failure, as long as the operation is completed. Default java aws-sdk waiter behaviour do not report on operation success, it only reports if operation completed or not. 
This pull request adds check wether operation was success, by comparing actual end state of CloudFormation stack with desired state 
- `UPDATE_COMPLETE` for update operation
- `CREATE_COMPLETE` for create operation
- ` DELETE_COMPLETE` for delete operation
Test pipeline has been modified to include testing stage for the failure reporting, conditionally executed based on `TEST_FOR_FAILURE` parameter value.
> CloudFormation step - validate end state

- vars/bakeAMI.groovy
- vars/lookupAMI.groovy
Adds support for providing an new config item called `baseAMIBranch` for bakeAMI and `amiBranch` for lookupAMI which filters AMI with BranchName tags. If no AMI with a given branch name is found it will return the latest `master` branch tag.
> filters out any the amis without any matching branches if any are found

- vars/samDeploy.groovy
- vars/samPackage.groovy
aws cli commands cloudformation package and deploy have a lot of functionality built into these commands and it would take some time to rewrite this in groovy as it is using change sets. Probably something that would be useful for other single stacks but for another day. 
The only limitation these commands is it requires a local template file, as in you cannot provide a s3 location. If the local file is too big a s3 location must be provided so it can upload it to s3. Which means the assumed account requires `s3:putObject` permission to the source bucket. Issue has been raise in cli repo https://github.com/aws/aws-cli/issues/3643
Sample package and deploy steps
```
stage('Compile cloudformation') {
steps {
script {
env['SHORT_COMMIT'] = env.GIT_COMMIT.substring(0,7)
if(env.BRANCH_NAME == …
```
> sam package and deploy using the cli

- vars/opsgenie.groovy
- vars/samDeploy.groovy
idea is to open an alert at the start of the deployment and close on success or raise the priority and alert of failure. This will capture the timeline and status of a deployment.
```groovy
stage('Deploy stack test') {
environment {
STACK_NAME = 'test-stack'
ENVIRONMENT = 'test'
}
steps {
opsgenie(
apiKey: env.OPSGENIE_APIKEY,
application: env.STACK_NAME,
environment: env.ENVIRONMENT,
details: [
deploymentType: 'cloudformation',
stackName: env.STACK_NAME,
region: env.AWS_REGION
]
)
samDeploy(
region: env.AWS_REGION,
stackName: env.STACK_NAME,
template: 'template.yaml',
source_bucket: env.SOURCE_BUCKET,
prefix: "cloudformation/${env.PROJECT_NAME}/${cf_version}",
parameters: [
'Environment' : env.ENVIRONMENT,
],
accountId: env.DEV_ACCOUNT_ID,
role: 'ciinabox'
)
}
post {
success { …
```
> opsgenie notifier

- vars/cloudformation.groovy
- vars/lookupSnapshot.groovy
- vars/ssmParameter.groovy
```groovy
cloudformation(
region: env.AWS_REGION,
action: 'create',
stackName: 'test',
stackState: '/mystacks'
)
```
Basically this will try and load any parameters from the ssm path `/mystacks/test/parameters` and then load them from `/mystacks/parameters` and only add parameters that didn't exist under the stack path.  
If you don't supply a templateUrl in the create it will look for a parameter `/mystacks/test/CfTemplateUrl` and then  `/mystacks/CfTemplateUrl` is that doesn't exist
```groovy
cloudformation(
region: env.AWS_REGION,
action: 'delete',
stackName: 'test',
stackState: '/mystacks'
)
```
This will save all the current stack parameters to the ssm path `/mystacks/test/parameters` also if the stack has a `CfTemplateUrl` output parameter it will store that  in …
> adding support for saving stack ssm params on deletion and restoring on create

- vars/cloudformation.groovy
Prints cloudformation errors on create/update/delete failures.
If a nested stack contains an error it will search that stack and report the error. Will only search 1 level deep.
```text
TIME: Thu Jan 10 05:22:00 GMT 2019
TYPE: AWS::CloudFormation::Stack
STACK: arn:aws:cloudformation:ap-southeast-2:857301260320:stack/dev-web/9e33c180-1497-11e9-ab02-0ae3f52010f8
STATUS: ROLLBACK_IN_PROGRESS
ERROR: The following resource(s) failed to create: [webservice]. . Rollback requested by user.
TIME: Thu Jan 10 05:22:00 GMT 2019
TYPE: AWS::CloudFormation::Stack
STACK: arn:aws:cloudformation:us-east-1:111111111111:stack/dev-web/9e33c180-1497-11e9-ab02-0ae3f52010f8
STATUS: CREATE_FAILED
ERROR: Embedded stack arn:aws:cloudformation:us-east-1:111111111111:stack/dev-web-webservice-1B88E8VFUYRSZ/a170eb20-149 …
```
> print cloudformation errors on failure

- vars/withIAMRole.groovy
If the variables were empty, they'd be assigned with 'null' in the finally{} block.
> withIAMRole: fix variable re-assignment bug.

- vars/copyAMI.groovy
Add option to encrypt an AMI on copy.
Specifying 'kmsKeyId' param in the config will use the provide kms key for encryption
Specifying 'encrypted' param in the config will use the default key
Specifying 'waitOnCopy' will wait for the AMI to complete copying before continuing
> Allow for AMI encryption on copy

- vars/cloudformation.groovy
Add retry policy for cloudformation api calls.
Use SDKDefaultRetryCondition and SDKDefaultBackoffStrategy with default max retries of 10
> Cfn max error retry

- vars/withMFA.groovy
Example
```groovy
withMFA(
credentials: 'iam-user-creds',
role: env.ASSUME_ROLE,
region: env.AWS_REGION,
accountId: env.DEV_ACCOUNT,
mfaToken: env.MFA_INPUT,
mfaId: env.MFA_ID
) {
cloudformation(
action: 'create',
region: env.AWS_REGION,
stackName: env.STACK_NAME,
templateUrl: env.TEMPLATE_URL,
parameters: [
'EnvironmentName': env.ENVIRONMET_NAME,
],
roleArn: env.CFN_ROLE
)
}
```
> new method to allow crossaccount mfa access

- src/com/base2/ciinabox/aws/Util.groovy
- vars/lookupAMI.groovy
- vars/packer.groovy
- vars/verifyAMIv2.groovy
- add new helper methods to lookup current region and account id
- look up from ssm parameter
- refactor ami ssm lookup to use lookupAMI method
- set env vars for the ami name and the bake id
- support ami lookup to allow testing before baking ami
- add `runlist` parameter to run recipe during test
- accept chef license
- destroy instance at the end of the run
> new features for AMI based methods

- src/com/base2/ciinabox/EcsTaskRunner.groovy
- src/com/base2/ciinabox/GetEcsContainerDetails.groovy
- src/com/base2/ciinabox/aws/AwsClientBuilder.groovy
- vars/startSelenium.groovy
- vars/stopSelenium.groovy
2 new methods and new library
- starts a selenium hub on fargate and retrieves the endpoint and exposes it through environment variables
```sh
SELENIUM_ENDPOINT -> ip address of fargate task
SELENIUM_PORT -> port of fargate task (4444)
SELENIUM_SOCKET -> ip:port
SELENIUM_TASK -> task arn exposed for cleanup
```
- containers are default selenium containers and defaults to version 3 
- default nodes of chrome and firefox
- all defaults overridable 
- stops the selenium fargate task and cleans up the task definition
- orchestration of the starting and stopping of the fargate task and registration and deregistration of the task definition
- built to support different short term build tasks to run on fargate
> start and stop a selenium hub in fargate

- vars/pipelineSeeder.groovy
The pipeline fails if either .job or .groovy files are missing from the pipelines directory. This PR will ignore those failures.
> pipeline seeder ignore missing job or groovy files

- vars/samDeploy.groovy
The AWS CLI exits with status code 255 if there's nothing to be done. See https://github.com/aws/serverless-application-model/issues/71
> samDeploy: don't exit on an empty changeset

- vars/cloudformation.groovy
This is more of a cry for help than actual a proper PR. 
It seems like one _cannot_ use `us-east-1` to find the location of a bucket outside that region. 
What happens is that my bucket is on `us-west-2`; I know need to create certain stacks in `us-east-1`. 
Turns out that attempting to run `s3headClient.getBucketLocation` with region `us-east-1` in a bucket in `us-west-2` simply doesn't work. Any other region works. 
I'm unsure how to address that? 
cc @aaronwalker  / @Guslington
> Not using us-east-1 for S3 getBucketLocation

- src/com/base2/ciinabox/InstanceMetadata.groovy
- src/com/base2/ciinabox/aws/Util.groovy
- vars/packer.groovy
- vars/startSelenium.groovy
- vars/stopSelenium.groovy
- vars/verifyAMIv2.groovy
- dont perform metadata and ec2 instance lookups if defaults are set
- refactor region lookup to use the region provider chain to support region lookup in fargate
- return better errors if networking details cannot be looked up
- apply fixes to packer, verifyAmiV2 and selenium methods
- make chef run in packer optional
> Bug fixes for networking lookups when Jenkins controller is running in Fargate

- vars/createChangeSet.groovy
- vars/executeChangeSet.groovy
When a "Gstring" / Groovy string is passed to the createChangeSet or executeChangeSet as the stack name, it returns null because instead of searching for (for example) stack-${params.envName} (stack-dev) it would  search for "stack-"
> Changeset - Fix GString encoding issue on stack status

- resources/Inspector.yaml
- vars/runInspector.groovy
Fixed issue where multiple stacks could not co-exist due to static naming.
> Inspector - fix static resource names when multiple runs happen at the same time

- resources/packer/install_7zip.ps1
The current version is not a valid package, thus causing packer to fail.
> Update 7zip to latest version

- src/com/base2/ciinabox/aws/AwsClientBuilder.groovy
- vars/executeChangeSet.groovy
- vars/washerySnapshotRestore.groovy
1. New client and waiter are created after 50 mins, future is also recreated **AFTER** client is created.
```groovy
if (count > 300) { //3000 seconds = 50 minutes, thread sleep is 10 secs so 300 iterations
cfclient = updateClient(clientBuilder, cfclient, config.region) 
waiter = updateWaiter(cfclient,changeSetType)
future = waiter.runAsync(
new WaiterParameters<>(new DescribeStacksRequest().withStackName(stackName)),
new NoOpWaiterHandler()
)
count = 0
}
```
1. RDS Client is now initialised after changeset deploy completes to avoid creds expiring within that timeframe.
```groovy
//Execute washery restore before rds client is initialised incase duration of changeset exceeds token duration
changeSetDeploy(
description: "Scheduled Washery DB Restore of snapshot ${config.snapshot}",
region: …
```
> changeset credential refresh after an hour

- src/com/base2/ciinabox/aws/IntrinsicsYamlConstructor.groovy
This change is required to support the 2.x snakeyaml plugin version but it is backwards compatible with the 1.x versions so shouldn't break older versions
> snakeyaml version changes

- vars/runInspector.groovy
This is so that the loop exits when inspector fails, and so it will then look up the results and output them even if it failed. Ideally the pipeline will then fail at the `onFail` condition later in the code.
> Add FAILED state to while loop

- src/com/base2/ciinabox/aws/CloudformationStack.groovy
At the time of writing this, the getBucketLocation(bucket), is querying a bucket at the ap-southeast-1 with the default region (us-east-01) and failing with:
`com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-southeast-1' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: 7MS6DSEXVCGSDAMC; S3 Extended Request ID: W+TtTvGGr631WQusxuCjqbwNqVbMYxOroPzHKGXIMuJZe28Z4mGbWM5wCyr94U1q7kAUoT9ccHw=; Proxy: null), S3 Extended Request ID: W+TtTvGGr631WQusxuCjqbwNqVbMYxOroPzHKGXIMuJZe28Z4mGbWM5wCyr94U1q7kAUoT9ccHw=`
I found a couple of reports in the past that this was a temporary issue, but it has lasted more than 48 hours.
This doesn't affect other regions. Tested …
> s3 client region header getBucketLocation  - not authorized in all regions 
